id: PCA14CD9F
initial_creation_type: input
source_metadata:
  Title: Sanskrit Manuscripts in China
  Editor: Ernst Steinkellner
  Publisher: China Tibetology Publishing House
  Place of Publication: Beijing, China
  Year: '2009'
  स्वप्नाध्याय:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:08:51.636394'
last_modified_at: '2022-03-08T17:08:51.636403'
